CREATE TABLE facebookInfo (
    idUser INT UNSIGNED NOT NULL
);
ALTER TABLE facebookInfo ADD CONSTRAINT PK_facebookInfo PRIMARY KEY(idUser);
ALTER TABLE facebookInfo ADD current_location VARCHAR(255);
ALTER TABLE facebookInfo ADD first_name VARCHAR(255);
ALTER TABLE facebookInfo ADD education_history TEXT;
ALTER TABLE facebookInfo ADD has_added_app BOOL;
ALTER TABLE facebookInfo ADD hometown_location VARCHAR(255);
ALTER TABLE facebookInfo ADD affiliations TEXT;
ALTER TABLE facebookInfo ADD books TEXT;
ALTER TABLE facebookInfo ADD birthday DATE;
ALTER TABLE facebookInfo ADD activities TEXT;
ALTER TABLE facebookInfo ADD about_me TEXT;
ALTER TABLE facebookInfo ADD pic_small VARCHAR(255);
ALTER TABLE facebookInfo ADD tv TEXT;
ALTER TABLE facebookInfo ADD work_history TEXT;
ALTER TABLE facebookInfo ADD wall_count VARCHAR(255);
ALTER TABLE facebookInfo ADD meeting_for VARCHAR(255);
ALTER TABLE facebookInfo ADD quotes TEXT;
ALTER TABLE facebookInfo ADD pic_big VARCHAR(255);
ALTER TABLE facebookInfo ADD notes_count TEXT;
ALTER TABLE facebookInfo ADD music TEXT;
ALTER TABLE facebookInfo ADD last_name VARCHAR(255);
ALTER TABLE facebookInfo ADD relationships_status VARCHAR(255);
ALTER TABLE facebookInfo ADD pic VARCHAR(255);
ALTER TABLE facebookInfo ADD status VARCHAR(255);
ALTER TABLE facebookInfo ADD profile_update_time DATETIME;
ALTER TABLE facebookInfo ADD interests TEXT;
ALTER TABLE facebookInfo ADD timezone VARCHAR(255);
ALTER TABLE facebookInfo ADD pic_square VARCHAR(255);
ALTER TABLE facebookInfo ADD political TEXT;
ALTER TABLE facebookInfo ADD is_app_user BOOL;
ALTER TABLE facebookInfo ADD movies TEXT;
ALTER TABLE facebookInfo ADD name VARCHAR(255);
ALTER TABLE facebookInfo ADD meeting_sex VARCHAR(255);
ALTER TABLE facebookInfo ADD religion VARCHAR(255);
ALTER TABLE facebookInfo ADD sex VARCHAR(255);
ALTER TABLE facebookInfo ADD significant_other_id TEXT;
ALTER TABLE facebookInfo ADD hs_info TEXT;
ALTER TABLE facebookInfo ADD CONSTRAINT fk_user_facebookUser FOREIGN KEY (idUser) REFERENCES user(idUser) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE facebookInfo DROP FOREIGN KEY fk_user_facebookUser;
ALTER TABLE facebookInfo ADD CONSTRAINT fk_user_facebookUser FOREIGN KEY (idUser) REFERENCES user(idUser) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE grouptable ADD CONSTRAINT PK_grouptable PRIMARY KEY(nickname,GROUPID);
ALTER TABLE proposedItemVotes MODIFY idVote INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE proposedItemVotes ADD CONSTRAINT fk_proposedItem_vote FOREIGN KEY (idProposedItem) REFERENCES proposeditem(idProposedItem) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE proposeditem CHANGE idProposedItem idItem INT UNSIGNED NOT NULL;
ALTER TABLE proposedItemVotes CHANGE idProposedItem idItem INT UNSIGNED NOT NULL;
ALTER TABLE auction CHANGE item_idItem idItem INT ;
ALTER TABLE auction ADD CONSTRAINT fk_auction_proposedItem FOREIGN KEY (idItem) REFERENCES proposeditem(idItem) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE bidderchips RENAME TO userChips;
ALTER TABLE userChips MODIFY changeDate DATETIME NOT NULL DEFAULT now();
ALTER TABLE userChips CHANGE User_idUser idUser INT NOT NULL;
ALTER TABLE userChips DROP PRIMARY KEY;
ALTER TABLE userChips ADD CONSTRAINT PK_userChips PRIMARY KEY(idUser,changeDate);
DROP INDEX fk_bidderChips_bidder ON userChips;
CREATE INDEX fk_userChips_user ON userChips (idUser);
ALTER TABLE userChips DROP FOREIGN KEY fk_bidderChips_bidder;
ALTER TABLE userChips DROP COLUMN bidder_idUser;
ALTER TABLE userChips ADD CONSTRAINT fk_user_userChips FOREIGN KEY (idUser) REFERENCES user(idUser) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE bid DROP FOREIGN KEY fk_userBid_User;
ALTER TABLE bid ADD CONSTRAINT fk_bid_User FOREIGN KEY (User_idUser) REFERENCES user(idUser) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE bid DROP FOREIGN KEY fk_userBid_auction;
ALTER TABLE bid ADD CONSTRAINT fk_bid_auction FOREIGN KEY (auction_idAuction) REFERENCES auction(idAuction) ON DELETE NO ACTION ON UPDATE NO ACTION;
