ALTER TABLE bid MODIFY bidDate TIMESTAMP NOT NULL;
ALTER TABLE auction MODIFY auctionPublishDate TIMESTAMP NOT NULL;
ALTER TABLE proposeditem MODIFY itemPublishDate TIMESTAMP NOT NULL;
ALTER TABLE user ADD registerDate TIMESTAMP NOT NULL;
ALTER TABLE proposedItemVotes ADD voteDate TIMESTAMP NOT NULL;
ALTER TABLE userChips MODIFY changeDate TIMESTAMP NOT NULL;
